import { CulvertDesign } from "../types/culvert";

/**
 * Reference example from Permattle Concrete Products Company
 * Blue Ridge Parkway: 5'-0" x 3'-0" x 58'-0" Single Cell
 */
export const DEFAULT_DESIGN: CulvertDesign = {
  geometry: {
    structureType: "box_culvert_4sided",
    cellCount: 1,
    span: 60,
    rise: 36,
    wallThickness: 8,
    topSlabThickness: 8,
    bottomSlabThickness: 8,
    haunchWidth: 8,
    haunchHeight: 8,
    fillHeight: 84,
    skewAngle: 0,
    bufferZoneWidth: 0,
    footingWidth: 0,
    footingDepth: 0,
    keywayWidth: 0,
    keywayDepth: 0,
  },
  units: {
    unitLength: 48,
    totalLength: 696,
    standardUnitCount: 12,
    inletUnitCount: 1,
    outletUnitCount: 1,
  },
  materials: {
    concreteStrength: 5000,
    rebarGrade: 60,
    rebarSpec: "ASTM A615",
    corrosionProtection: false,
    gasketSpec: "ASTM C1677",
    coverTopSlabExterior: 2.5,
    coverTopSlabInterior: 2.0,
    coverBottomSlabExterior: 1.5,
    coverBottomSlabInterior: 1.5,
    coverWallExterior: 1.5,
    coverWallInterior: 1.5,
  },
  reinforcement: [
    {
      id: "1",
      barMark: "A1",
      barSize: 4,
      quantity: 7,
      spacing: 8,
      length: 24,
      shape: "L",
      leg1: 12,
      leg2: 12,
      location: "Top slab haunch corners",
      steelType: "black",
      zone: "haunch",
    },
    {
      id: "2",
      barMark: "A2",
      barSize: 4,
      quantity: 7,
      spacing: 8,
      length: 24,
      shape: "L",
      leg1: 12,
      leg2: 12,
      location: "Bottom slab haunch corners",
      steelType: "black",
      zone: "haunch",
    },
    {
      id: "3",
      barMark: "A100",
      barSize: 4,
      quantity: 7,
      spacing: 8,
      length: 58,
      shape: "straight",
      leg1: null,
      leg2: null,
      location: "Top slab interior",
      steelType: "black",
      zone: "top_slab",
    },
    {
      id: "4",
      barMark: "A200",
      barSize: 4,
      quantity: 7,
      spacing: 8,
      length: 58,
      shape: "straight",
      leg1: null,
      leg2: null,
      location: "Bottom slab interior",
      steelType: "black",
      zone: "bottom_slab",
    },
    {
      id: "5",
      barMark: "A300",
      barSize: 4,
      quantity: 7,
      spacing: 8,
      length: 82,
      shape: "straight",
      leg1: null,
      leg2: null,
      location: "Top slab exterior",
      steelType: "black",
      zone: "top_slab",
    },
    {
      id: "6",
      barMark: "A400",
      barSize: 4,
      quantity: 7,
      spacing: 8,
      length: 82,
      shape: "straight",
      leg1: null,
      leg2: null,
      location: "Bottom slab exterior",
      steelType: "black",
      zone: "bottom_slab",
    },
    {
      id: "7",
      barMark: "B1",
      barSize: 4,
      quantity: 7,
      spacing: 8,
      length: 40,
      shape: "straight",
      leg1: null,
      leg2: null,
      location: "Wall exterior",
      steelType: "black",
      zone: "left_wall",
    },
    {
      id: "8",
      barMark: "B3",
      barSize: 4,
      quantity: 7,
      spacing: 8,
      length: 31,
      shape: "straight",
      leg1: null,
      leg2: null,
      location: "Wall interior",
      steelType: "black",
      zone: "right_wall",
    },
    {
      id: "9",
      barMark: "C1",
      barSize: 4,
      quantity: 4,
      spacing: 0,
      length: 46,
      shape: "straight",
      leg1: null,
      leg2: null,
      location: "Longitudinal top",
      steelType: "black",
      zone: "longitudinal",
    },
    {
      id: "10",
      barMark: "C100",
      barSize: 4,
      quantity: 4,
      spacing: 0,
      length: 46,
      shape: "straight",
      leg1: null,
      leg2: null,
      location: "Longitudinal wall",
      steelType: "black",
      zone: "longitudinal",
    },
    {
      id: "11",
      barMark: "C200",
      barSize: 4,
      quantity: 4,
      spacing: 0,
      length: 46,
      shape: "straight",
      leg1: null,
      leg2: null,
      location: "Longitudinal bottom",
      steelType: "black",
      zone: "longitudinal",
    },
  ],
  project: {
    projectName: "Blue Ridge Parkway Box Culvert",
    clientName: "Permattle Concrete Products",
    projectNumber: "BRP-2024-001",
    engineer: "",
    location: "Blue Ridge Parkway, VA",
    stateStandard: "VDOT",
    dateCreated: new Date().toISOString().split("T")[0],
    dateModified: new Date().toISOString().split("T")[0],
    status: "draft",
    drawnBy: "",
    checkedBy: "",
    approvedBy: "",
    revisionNumber: 0,
  },
};
